### PR TITLE
feat: render list inside a viewport

### PR DESCRIPTION
**Pull request by caarlos0**
allowing scrolling et al.

almost thinking we could use the list model, add a keybind to copy the id, etc...

wdyt?

### CODE REVIEW

**Comment by bashbunni** [comment]
I could see it being quite helpful being able to fuzzy find a conversation, then copy the ID. :thought_balloon:

**Comment by cloudbridgeuy** [comment]
It would be nice to have this embedded. I use it all the time thought `fzf` like this:

```
mods --list --raw 2>&1 | fzf -m --preview 'mods -s $(echo -n {} | awk "{print $1}")' --preview-window=right:60% --height 100% --border
```

**Comment by caarlos0** [comment]
@bashbunni good idea, done

**Comment by bashbunni** [comment]
added notification msg to show user that the ID was copied to clipboard (yoinked from freeze)
image

**Pull request merged**
