### PR TITLE
feat: add ability to continue, save, and manage conversations

### PR DESCRIPTION
**Pull request by im-aIex**
Adds `--continue`/`-c` to allow continuing the conversation from the last prompt/response.

Stores the most recent conversation in a temp file unless `--no-cache` is specified.

### CODE REVIEW

**Comment by toby** [comment]
Hey, thanks for this we should definitely support conversations! 

I think we should have a few additional features though. This is writing the cache to the global temp dir with the name `mods.gob`. It would be easy to overwrite that if multiple users ran `mods` and we should make sure that each user's data is only viewable by them. We can store the data in `$XDG_DATA_HOME/mods/conversations`. We're using [this lib](https://pkg.go.dev/github.com/adrg/xdg#section-readme) to calculate xdg dirs.

We should ultimately support multiple conversations, but that will most likely involve TUI work and a db for storing/choosing them.

**Comment by im-aIex** [comment]
Thanks for the heads up on `$XDG_DATA_HOME`, I hadn't noticed the library and on windows `os.TempDir()` is in a user folder.

I threw together some basic save/load functionality just based on the file cache, but I agree a TUI+db would be ideal.

**Comment by toby** [comment]
This is really awesome! I love being able to save and continue multiple conversations.

We should use `xdg.DataHome` instead of `xdg.Home` though. I think ideally you could configure the cache directory in the `mods.yml` but for now we can just use `xdg.DataHome/mods/conversations`.

**Comment by toby** [comment]
Also just ran the linter and it caught some missing error checks, but other than that and the switch to `xdg.DataHome` we should be good to go.

**Comment by toby** [comment]
Going to merge this now, thank you so much! We may end up tweaking some of the flags/docs but it's working great.

**Pull request merged**
