### PR TITLE
feat: azure openai support

### PR DESCRIPTION
**Pull request by sozercan**
adds azure openai support

### CODE REVIEW

**Review by toby — COMMENTED** [review]
Hi, thanks for this! Can you try just specifying the Azure endpoint in the settings file with`mods -s`? It *should* work. I’d rather keep the code as non-service specific as possible.

**Comment by sozercan** [comment]
@toby unfortunately not due to difference in apis. this is why it's a separate path in https://github.com/sashabaranov/go-openai/blob/62eb4beed29f4e821a59088f043fb56761d79fa7/config.go#L53

**Comment by toby** [comment]
Ah I see, it looks like the [api type is just a string](https://github.com/sashabaranov/go-openai/blob/62eb4beed29f4e821a59088f043fb56761d79fa7/config.go#L20) so we could probably just add an `api-type` key to the api in the config. We may also want to put the `token-env-var` in the config, so you could set it to `OPENAI_API_KEY` or `AZURE_OPENAI_ENDPOINT` (or something else). Then we wouldn't have to have any special cases in the code and it could all be done in `mods -s`.

**Comment by philipsd6** [comment]
You should also make sure this supports the config.AzureModelMapperFunc, as we have deployments that are not named the same as the model. Or will the `mods --settings` support this via the api models key aliases maybe?

**Comment by toby** [comment]
I added a few things to this commit to push more of the work into the config file. I'll probably clean this up a bit more, but if anyone wants to take a look and give some feedback, it's here:

https://github.com/charmbracelet/mods/compare/main...azure-openai

Now you can set the `AZURE_OPENAI_KEY` env var, update the Azure endpoints in the config with `mods -s` then use the models with the `-m` flag. If there's a name collision with the models in different APIs, mods will prefer the API defined earlier in the YAML. You can still reference the model with a unique alias or by specifying the api directly with `--api`.

I haven't tested the Azure stuff because I'm waiting on access approval, but it should work according to the openai library docs.

New settings file format:

**Comment by toby** [comment]
Also, @philipsd6 you should be able to just specify your custom model name as the key in the YAML file with `mods -s`.

**Comment by philipsd6** [comment]
> Also, @philipsd6 you should be able to just specify your custom model name as the key in the YAML file with `mods -s`.

OK @toby, I built `mods` from your `azure-openai` branch and used a config like this:

```yaml
apis:
  azure:
    api-key-env: OPENAI_API_KEY  # I use the same env var for Azure :)
    base-url: https://my-example-resource.openai.azure.com
    models:
      MyGPT35:
        aliases: ["az35t"]
        max-input-chars: 12250
        fallback:
```

&hellip;and it works, with either the alias or the key as the `--model` parameter. The only difference with your screenshot above is that the `base-url` should not include the path (as that's handled by the `go-openai` internally.)

Thanks!

**Comment by toby** [comment]
Thank you so much for testing @philipsd6. I fixed the `base-url` based on your note as well. I'll merge this and we can put it in the next release (should be soon).

**Pull request closed without merging**
